# Generated by Django 5.0 on 2024-01-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invmanage", "0002_alter_producttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecification",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invmanage.producttype",
            ),
        ),
    ]
