# Generated by Django 5.0 on 2024-01-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invmanage", "0003_alter_productspecification_product_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
    ]
